#define REPORT_ID_KEYBOARD          'K'
#define REPORT_ID_SYSTEM_CONTROL    'S'
#define REPORT_ID_CONSUMER_DEVICE   'C'


#define USB_KEY_A   0x04
#define USB_KEY_B   0x05
#define USB_KEY_C   0x06
#define USB_KEY_D   0x07
#define USB_KEY_E   0x08
#define USB_KEY_F   0x09
#define USB_KEY_G   0x0A
#define USB_KEY_H   0x0B
#define USB_KEY_I   0x0C
#define USB_KEY_J   0x0D
#define USB_KEY_K   0x0E
#define USB_KEY_L   0x0F
#define USB_KEY_M   0x10
#define USB_KEY_N   0x11
#define USB_KEY_O   0x12
#define USB_KEY_P   0x13
#define USB_KEY_Q   0x14
#define USB_KEY_R   0x15
#define USB_KEY_S   0x16
#define USB_KEY_T   0x17
#define USB_KEY_U   0x18
#define USB_KEY_V   0x19
#define USB_KEY_W   0x1A
#define USB_KEY_X   0x1B
#define USB_KEY_Y   0x1C
#define USB_KEY_Z   0x1D

#define ENTER       0x28
#define BACKSPACE   0x2A
#define SPACE       0x2C
#define CAPS_LOCK   0x39
#define SCROLL_LOCK 0x47
#define HOME        0x4A
#define DELETE      0x4C
#define END         0x4D
#define RIGHT       0x4F
#define LEFT        0x50
#define DOWN        0x51
#define UP          0x52
#define NUM_LOCK    0x53